apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-analytics
  template:
    metadata:
      labels:
        app: alpha-analytics
    spec:
      containers:
        - name: app
          image: jairleo95/alpha-analytics:1.2.2
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql-service
            - name: DB_NAME  # Setting Database name
              value: alpha_analytics
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: password

          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-analytics
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: alpha-analytics